test passed on local

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -17,21 +17,17 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Set up Xcode
-        run: |
-          sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
-
       - name: Install Dependencies
         run: |
-          cd uusr
+          cd usr || { echo "Directory 'usr' not found!"; exit 1; }
           xcodebuild -resolvePackageDependencies
 
       - name: Build App
         run: |
-          cd uusr
-          xcodebuild -scheme uusr -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 14' build
+          cd usr || { echo "Directory 'usr' not found!"; exit 1; }
+          xcodebuild -scheme usr -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16' build
 
       - name: Run Tests
         run: |
-          cd uusr
-          xcodebuild test -scheme uusr -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 14'
+          cd usr || { echo "Directory 'usr' not found!"; exit 1; }
+          xcodebuild test -scheme usr -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16'
